command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
env:
  - name: CATALOG_NAME
    value: lr_dev_aws_us_catalog
  - name: SCHEMA_NAME
    value: bricksurance_re
  - name: WAREHOUSE_ID
    valueFrom: sql_warehouse
  - name: USE_CACHE
    value: "true"
  - name: GENIE_SPACE_ID
    value: "01f168f7b5f91bcb836e7769db6c7586"
  - name: DASHBOARD_ID
    value: "01f17040eb911cb584f90045debe0d9f"
  - name: FM_ENDPOINT
    value: databricks-claude-sonnet-4-6
